DNIObligatorio = "El documento es obligatorio."
MailObligatorio = "El mail es obligatorio."
PassObligatorio = "Ingrese una contraseña."
EnviarCorreo = "Se ha enviado un mail a su correo."
CorreoInvalido = "Ingrese un mail válido."
CredencialesInvalidas = "· Credenciales inválidas"
AgregarSucursal = "Sucursal creada con éxito."
EditarSucursal = "Sucursal editada con éxito."
"""
CAJA
"""
AgregarCaja = "Caja creada con éxito."
EditarCaja = "Caja editada con éxito."
CajaAbierta = "Usted se encuentra trabajando con la caja {codigo_caja}."
CajaCerrada = "Apertura de caja {codigo_caja}"
CajaBloqueada = "La caja {codigo_caja} se ha bloqueado"
NoPuedeOperarCaja = "No podrá operar con esta caja."
DesbloquearCaja = "Para desbloquearse comuníquese con el área correspondiente al 1234-1234"

TituloDeclaracionJurada = "Declaración Jurada {num_declaracion} para el cierre de la caja {codigo_caja}"
