from selenium.webdriver.common.by import By
from page_objects.base_page import Locator
import time


class VerificarAvisoLocators:
    aprobar_BTN = Locator(By.XPATH, "//button[@id='aprobar']")
    cierre_ventana_BTN = Locator(By.XPATH,"//div[@class='modal-dialog modal-lg']//span[contains(text(),'×')]")
    mensaje_MSJ = Locator(By.XPATH, "//div[@class='flash-notice']")
    autos_INP = Locator(By.ID,"AvisoVerificacionType_autos")
    causante_INP = Locator(By.ID, "AvisoVerificacionType_causante")
    opcion_default_OPT = Locator(By.XPATH, "//li[@class='opt selected']//label[contains(text(),'--Seleccionar--')]")
    opcion_subtipo_LBL = Locator(By.XPATH, "//label[contains(text(),'Sin Subtipo de aviso')]")
    fechalimitepago_INP = Locator(By.ID, "AvisoVerificacionType_fechaLimitePago")
    lupa_ult_aviso_BTN = Locator(By.XPATH, "//tr[1]//td[11]//a[1]//i[1]")
    dias_INP = Locator(By.XPATH, "//input[@id='AvisoVerificacionType_cantDiasAviso']")
    fecha_publicar_INP = Locator(By.ID, "AvisoVerificacionType_fechaPublicacion")
    modalidad_pago_LBL = Locator(By.XPATH, "//label[contains(text(),'Modalidad pago')]")
    fecha_firma_INP = Locator(By.ID, "AvisoVerificacionType_fechaFirmaActoAdministrativo")
    descargar_texto_BTN = Locator(By.XPATH, "//h6[@class='panel-title']//i[@class='fa fa-download text-success']")
    decargar_doc_BTN = Locator(By.XPATH, "//h5[@class='panel-title']//i[@class='fa fa-download text-success']")
    doc_no_existe_LBL = Locator(By.XPATH, "//i[@class='fa fa-exclamation-triangle fa-4x text-danger']")
    guardar_BTN = Locator(By.XPATH, "//button[@id='guardar']")
    guardar_Pend_PUB_BTN = Locator(By.XPATH, "//button[@id='guardarFechaPub']")
    texto_dias_LBL = Locator(By.XPATH, "//li[contains(text(),'Dias a publicar incorrecto')]")
    texto_fecha_LBL = Locator(By.XPATH, "//li[contains(text(),'Fecha de publicacion requerida')]")
    texto_firma_LBL = Locator(By.XPATH, "//li[contains(text(),'Valor requerido')]")
    info_gral_LBL = Locator(By.XPATH, "//p[contains(text(),'Información general')]")
    anio_exp_jub_LBL = Locator(By.XPATH, "//li[contains(text(),'Año expediente judicial requerido')]")
    nro_exp_jud_LBL = Locator(By.XPATH, "//li[contains(text(),'Nro expediente judicial requerido')]")
    buscar_BTN = Locator(By.XPATH, "//button[@class='btn btn-default btn-sm']")
    cerrar_sesion = Locator(By.XPATH, "//a[@class='pull-left user-text']")
    subtipo_SEL = Locator(By.XPATH, '//span[contains(text(),"Seleccionar")]')
    sin_subtipo_OP = Locator(By.XPATH, "//label[contains(text(),'Sin Subtipo de aviso')]")
    fecha_limite_pago_INP = Locator(By.ID, "AvisoVerificacionType_fechaLimitePago")
    anio_exepdiente_INP = Locator(By.ID, "AvisoVerificacionType_anioExpedienteJudicial")
    nro_expediente_INP = Locator(By.ID, "AvisoVerificacionType_nroExpedienteJudicial")
    organismo_SEL = Locator(By.ID, "AvisoVerificacionType_organismo")
    sin_valor_subtipo_SPAN = Locator(By.XPATH, "//span[contains(text(),'--Seleccionar--')]")
    titulo_INP = Locator(By.ID, "AvisoVerificacionType_titulo")
    documento_aviso_LBL = Locator(By.XPATH, "//a[@class='documento_title']")
    TEMP_VISUALIZAR_AVISO = Locator(By.XPATH, "//td[contains(text(),'{id_aviso}')]/parent::tr//a")
    TEMP_LOCATOR_ESTADO = Locator(By.XPATH, "//td[contains(text(),'{id_aviso}')]//preceding::td[1]")
    suplemento_SEL = Locator(By.ID, "AvisoVerificacionType_ordenArmadoSuplemento")
    rubro_SEL = Locator(By.ID, "AvisoVerificacionType_rubro")
    dia_31_BTN = Locator(By.XPATH, "//td[@class='old today day']")

